const images = {
    background: require('../images/background.png'),
    loginbackground: require('../images/base.png'),
    baseLogo: require('../images/base-logo.png'),
    emailIcon: require('../images/email-icon.png'),
    fullName: require('../images/fullname-icon.png'),
    password: require('../images/password-icon.png'),
    facebookButton: require('../images/join-with-facebook-button.png'),
    dollarIcon: require('../images/dollar-icon.png'),
    importfbbutton: require('../images/import-from-facebook-button.png'),
    dbbackground: require('../images/dashboard-screen-base.png'),
    dbtoplogo: require('../images/dashboard-screen-diagram.png'),
    inboxIcon: require('../images/dashboard-screen-inbox-tab.png'),
    upcomingIcon: require('../images/dashboard-screen-upcoming-tab.png'),
    colenderIcon: require('../images/dashboard-screen-calendar-tab.png'),
    donateIcon: require('../images/dashboard-screen-donate-tab.png'),
    gifthistoryIcon: require('../images/dashboard-screen-gift-history-tab.png'),
    settingsIcon: require('../images/dashboard-screen-settings-tab.png'),
    addfriendIcon: require('../images/dashboard-screen-add-friends-tab.png'),
    logoutIcon: require('../images/dashboard-screen-logout-tab.png'),
    dropdownArrow: require('../images/dropdown-arrow.png'),
    payPalBtn: require('../images/link-with-paypal-button.png'),
    addBtn: require('../images/settings-screen-friends-tab-plus-icon.png'),
    dashboardIcon: require('../images/dashboard-icon.png'),
    backIcon: require('../images/back-icon.png'),
    checkedcheckbox: require('../images/donate-screen-checkbox.png'),
    uncheckedcheckbox: require('../images/donate-screen-uncheckbox.png'),
    fbicon: require('../images/settings-screen-friends-tab-facebook-icon.png'),
    crossicon: require('../images/settings-screen-friends-tab-cross-icon.png'),
    editicon: require('../images/settings-screen-friends-tab-edit-icon.png'),
    placeholderImage: require('../images/placeholderImage.png'),
    giftrecieved: require('../images/gif-history-screen-total-received-tab-icon.png'),
    giftsent: require('../images/gif-history-screen-total-sent-tab-icon.png'),
    giftdonation: require('../images/gif-history-screen-total-donations-tab-icon.png'),
}
export default images
